apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ template "registry.fullname" . }}
  labels:
    app.kubernetes.io/component: registry
    {{- include "registry.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    app.kubernetes.io/component: registry
    {{- include "registry.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: registry
        {{- include "registry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: {{ include "registry.image" .}}
        imagePullPolicy: IfNotPresent
        name: registry
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"