apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 5000
  - port: 443
    name: https
    targetPort: 443
  selector:
    app.kubernetes.io/component: registry
    {{- include "registry.selectorLabels" . | nindent 4 }}