# Default values for registry chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  registry:
    repository: docker.io/registry
    tag:

commonLabels: {}
