{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "system:%s" (include "amazon-cloudwatch-logs.fullname" .) }}
  labels:
    {{- include "amazon-cloudwatch-logs.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
      - nodes
      - nodes/proxy
    verbs:
      - get
      - list
      - watch
{{- end -}}